# Generated by Django 6.0.3 on 2026-05-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('emergency', 'Emergency'), ('surgery', 'Surgery'), ('outpatient', 'Outpatient')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics')], max_length=50),
        ),
    ]
